version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3.3-node
        environment:
          RAILS_ENV: test
          POSTGRES_CONNECTION: postgresql://ubuntu:@127.0.0.1:5432/circle_ruby_test
      - image: postgres:9.5
        environment:
        - POSTGRES_USER: ubuntu
        - POSTGRES_DB: circle_ruby_test
    steps:
      - checkout
      # Restore bundle cache
      - restore_cache:
          key: rails-{{ checksum "wcc-contentful.gemspec" }}

      # Bundle install dependencies
      - run: bundle install --path /tmp/vendor/bundle

      # Store bundle cache
      - save_cache:
          key: rails-{{ checksum "wcc-contentful.gemspec" }}
          paths:
            - /tmp/vendor/bundle

      # run Danger
      # - type: shell
      #   command: |
      #     bundle exec danger

      # run rubocop
      - type: shell
        command: |
          bundle exec rubocop

      # Run rspec in parallel
      - type: shell
        command: |
          bundle exec rspec --profile 10 \
                            --format RspecJunitFormatter \
                            --out test_results/rspec.xml \
                            --format documentation \
                            --order rand \
                            $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

      # Save test results for timing analysis
      - store_test_results:
          path: test_results

